leftnav:
- identifier: 272e4965-1a12-a2a2-75c8-28826a0a35a4
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: df24edda-573c-77ee-77a6-be0850a6e691
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 5e7dafe4-8f73-8fc4-0cba-aac1b7f74596
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  name: Assignments
  pageRef: /pages/assignments/
  weight: 40
- identifier: 191d71e8-6fec-22c9-e577-101115af38c9
  name: Weekly Journal Entries
  pageRef: /pages/assignments/weekly-journal-entries
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 50
- identifier: 06244214-e577-8675-3ce2-a779116b0425
  name: Corners and Squares
  pageRef: /pages/assignments/corners-and-squares
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 60
- identifier: f63923fe-a36a-1a4f-4105-23263158e3a0
  name: Baseline Analysis
  pageRef: /pages/assignments/baseline-analysis
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 70
- identifier: bcf2edca-4f68-b56a-da38-7cb4bf6e0855
  name: Detailed Research, Analysis, and Planning
  pageRef: /pages/assignments/detailed-research-analysis-and-planning
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 80
- identifier: 008000ef-d22e-9023-f883-ce3b685ed5f9
  name: Formulation of Final Plan
  pageRef: /pages/assignments/formulation-of-final-plan
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 90
- identifier: 5d5da985-2339-b23f-c05d-5737c0f5ffc2
  name: Oral Presentation
  pageRef: /pages/assignments/oral-presentation
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 100
- identifier: ba12b00d-4ea1-ecf4-6735-adff62b7361d
  name: Poster
  pageRef: /pages/assignments/poster
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 110
- identifier: e15a85c0-f4b0-afcb-1495-badeadca5de0
  name: Final Report
  pageRef: /pages/assignments/final-report
  parent: 08b4fc6c-d34c-a81d-e0fb-036b5ed8be07
  weight: 120
- identifier: 6e80a167-da1f-4d16-1477-3d8781591d44
  name: Projects
  pageRef: /pages/projects
  weight: 130
- identifier: e4257a67-77b4-216f-41b2-deab0b53a919
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 140
- identifier: afdcc7a4-75bc-c296-b94a-c28d54efed82
  name: Image Gallery
  pageRef: /pages/image-gallery
  weight: 150
